# Calculate the total revenue generated by two product categories in a store 
import numpy as np
category1_revenue = np.array([500,600,700,550])
category2_revenue = np.array([450,700,800,900])
Total_Revenue = category1_revenue + category2_revenue
print("Total Revenue : ",Total_Revenue)

# Calculate the profit made by a company 
revenue = np.array([10000,12000,11000,10500])
expenses = np.array([4000,5000,4500,4800])
profit = revenue - expenses
print("Profit : ",profit) 

# Determine which products in a store are out of stock (quantity is 0)
inventory = np.array([10, 0, 5, 0, 20, 0])
out_of_stock = inventory[inventory == 0]
print("Out of Stock products : ",out_of_stock)

# Calculate the total cost of items in a shopping cart, considering
# the quantity and price per item.

quantity = np.array([2,3,4,1])
price_per_item = np.array([10.0,5.0,8.0,12.0])
total_cost = quantity * price_per_item
print("Total Cost of Items : ",total_cost)
